---
- name: Cau hinh static route
  hosts: Router
  gather_facts: no

  tasks:
    - name: config static route
      cisco.ios.ios_static_route:
        prefix: "{{ item.ip }}" 
        mask: "{{ item.netmask }}"
        next_hop: " {{ item.nexthop }} "
      with_items: " {{ static }}"
